### ISSUE TITLE
Feedback Score

### ISSUE THREAD

**Issue by tjoye20** [PatLeroux/f1-3-c2p1-colmar-academy#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 3 - Meets Expectations
* _Comment(s):_ Your HTML code is very organized and clean; `section-header` is not a valid HTML element though, Line 96 in your `index.html`.
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 3 - Meets Expectations
* _Comment(s):_ When I adjust the Chrome browser to change it to mobile view, your website doesn't match the specs. They probably "match" when you manually resize your browser window, but that won't work on a mobile view. You were only missing one line in your HTML file that would make it work for the mobile view: `<meta name="viewport" content="width=device-width, initial-scale=1.0">` [Link](https://www.w3schools.com/css/css_rwd_viewport.asp)
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 3 - Meets Expectations
* _Comment(s):_ The media queries didn't kick in with the correct styles to match the specs for mobile view because of the previous comment. 
 
### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 4 - Exceeds Expectations
 
### Overall Score: 13/16
Good effort on this, Patrick. Your HTML and CSS code is really clean and easy to follow, and I can tell you have a strong grasp of the basics. The only thing that was missing was that `meta` tag to set the viewport so your media queries can work correctly on mobile devices.

**Comment by PatLeroux** [comment]
So did i pass the course ? Will i receive my certificate ?

**Comment by tjoye20** [comment]
@PatLeroux Yes. [Reference](https://help.codecademy.com/hc/en-us/articles/360005899713-Earning-a-Credential-of-Completion?mobile_site=true)
